### ISSUE TITLE
create account error

### ISSUE THREAD

**Issue by IEEE756** [kesar/ethereum-php#12]
when I run the following code , the errors occured as the screenshot shows
`$account = $client->personal()->newAccount('test');
echo $account->toString() , PHP_EOL;
echo $client->personal()->unlockAccount($account, 'test', 20) , PHP_EOL;
`
![snip20180607_99](https://user-images.githubusercontent.com/11880504/41085698-59853b54-6a6a-11e8-8478-88fe4ccb30f6.png)

**Comment by kesar** [comment]
is it client properly connected to an ethereum node? try with a different account name in case that test was already used.

$client = new EthereumClient('http://localhost:8545'); ?

**Comment by vikasprogrammer** [comment]
I am getting the same error.

**Comment by vikasprogrammer** [comment]
I tried using Parity's light node which I have installed locally.

**Comment by shoxabbos** [comment]
You need to enable the personal API over RPC. Do this by starting geth with

geth --rpc --rpcapi "db,eth,net,web3,personal"

**Comment by shoxabbos** [comment]
![image](https://user-images.githubusercontent.com/8403807/44209257-5d695180-a17c-11e8-9f6f-cd6913e3a579.png)
