### ISSUE TITLE
Amount property of Wei type should be INTEGER, not FLOAT

### ISSUE THREAD

**Issue by sonofliberty** [kesar/ethereum-php#15]
As Wei is the base unit of ether, the amount property should be integer and not float. I'm running into unnecessary precision issues.

**Comment by kesar** [comment]
great suggestion, are you planning to open a PR? I would merge it  👍

**Comment by sonofliberty** [comment]
Alright, I created the PR. :-)

**Comment by kesar** [comment]
anyhow it should be most likely bigint using some library, kudos to @tspop
