### ISSUE TITLE
Cannot send more than 9.223372036854775807 ETH

### ISSUE THREAD

**Issue by sonofliberty** [kesar/ethereum-php#17]
PHP's maximum integer value (64 bit) is 9,223,372,036,854,775,807.

**Comment by kesar** [comment]
Yes, its a known problem. I think we may need to use something like: https://github.com/phpmath/biginteger but I dont have too much time lately... if anyone wants to contribute with a PR will be very welcome <3

**Comment by sonofliberty** [comment]
Resolved with #18
